/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_dahan_gonzalez;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Orly
 */
public class Interfaz extends javax.swing.JFrame {
    
    LogicaThread logica;
    
   
    /**
     * Creates new form Interfaz
     * @param logica
     */
    public Interfaz(LogicaThread logica) {
        this.logica = logica;
        initComponents();
        this.intCantR.setText("0");
        this.intCantP.setText("0");
        this.intCantM.setText("0");
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        intCantR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intCantP = new javax.swing.JTextField();
        intCantM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prodRuedas = new javax.swing.JTextField();
        prodPara = new javax.swing.JTextField();
        prodMotor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        contratarP = new javax.swing.JButton();
        despedirP = new javax.swing.JButton();
        contratarM = new javax.swing.JButton();
        despedirM = new javax.swing.JButton();
        contratarR = new javax.swing.JButton();
        despedirR = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cantEnsam = new javax.swing.JTextField();
        contratarEnsambladores = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        carrosTerm = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        statusJefe = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        statusGerente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        diasDespacho = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(189, 189, 189));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMULADOR DE PROCESO DE FABRICACIÓN DE IBMW");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("DISPONIBLIDAD EN EL ALMACÉN ");

        jLabel3.setText("Ruedas");

        jLabel4.setText("Parabrisas");

        jLabel5.setText("Motores");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("DISPONIBLIDAD DE PRODUCTORES ");

        jLabel7.setText("Ruedas");

        jLabel8.setText("Parabrisas");

        jLabel9.setText("Motores");

        prodPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodParaActionPerformed(evt);
            }
        });

        contratarP.setText("CONTRATAR");
        contratarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarPActionPerformed(evt);
            }
        });

        despedirP.setText("DESPEDIR");
        despedirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirPActionPerformed(evt);
            }
        });

        contratarM.setText("CONTRATAR");
        contratarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarMActionPerformed(evt);
            }
        });

        despedirM.setText("DESPEDIR");
        despedirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirMActionPerformed(evt);
            }
        });

        contratarR.setText("CONTRATAR");
        contratarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarRActionPerformed(evt);
            }
        });

        despedirR.setText("DESPEDIR");
        despedirR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodRuedas, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(intCantM, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(intCantR, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(contratarP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(despedirP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6)
                                .addComponent(prodMotor)
                                .addComponent(intCantP)
                                .addComponent(prodPara))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contratarM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(despedirM, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(contratarR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(despedirR)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intCantR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(intCantP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(intCantM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(prodRuedas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(despedirR)
                    .addComponent(contratarR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodPara, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contratarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(despedirP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contratarM)
                            .addComponent(despedirM))
                        .addContainerGap())))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("DISPONIBILIDAD DE ENSAMBLADORES");

        cantEnsam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantEnsamActionPerformed(evt);
            }
        });

        contratarEnsambladores.setText("CONTRATAR");
        contratarEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarEnsambladoresActionPerformed(evt);
            }
        });

        jButton2.setText("DESPEDIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("CONFIGURAR ENSAMBLADORES");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("CANTIDAD DE CARROS ENSAMBLADOS");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("TRABAJO REALIZADO POR EL JEFE");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("TRABAJO QUE REALIZA EL GERENTE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("DIAS QUE FALTAN PARA EL DESPACHO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diasDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(statusGerente)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(statusJefe)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(carrosTerm, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cantEnsam)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(contratarEnsambladores)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel15))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantEnsam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contratarEnsambladores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carrosTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diasDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratarEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarEnsambladoresActionPerformed
        // TODO add your handling code here:
        boolean aux = false;
        if(this.logica.getEnsInicial()< this.logica.getMaxEns()){
            this.logica.setEnsInicial(this.logica.getEnsInicial()+1);
            this.logica.getInterfaz().getCantEnsam().setText(Integer.toString(this.logica.getEnsInicial()));
        }
        
        for (int i = 0; i < this.logica.getEnsInicial(); i++) {
            if (this.logica.getEnsamblador()[i]== null && !aux) {
                System.out.println("SE CONTRATO A UN ENSAMBLADOR");
               this.logica.getEnsamblador()[i] =new Ensamblador (this.logica.getSEMR(), this.logica.getSPR(), this.logica.getSCR(), this.logica.getSEMP(), this.logica.getSPP(), this.logica.getSCP(),this.logica.getSEMM(), this.logica.getSPM(), this.logica.getSCM(), this.logica, this.logica.getSEMD());
               this.logica.getEnsamblador()[i].start();
               aux = true;
               break;
            }
        }
    }//GEN-LAST:event_contratarEnsambladoresActionPerformed

    private void contratarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarMActionPerformed
        // TODO add your handling code here:
        
        boolean aux = false;
        if(this.logica.getProvInicialM()< this.logica.getMaxProvM()){
            this.logica.setProvInicialM(this.logica.getProvInicialM()+1);
            this.logica.getInterfaz().getProdMotor().setText(Integer.toString(this.logica.getProvInicialM()));
        }
        
        for (int i = 0; i < this.logica.getProvInicialM(); i++) {
            if (this.logica.getpMotor()[i]== null && !aux) {
                System.out.println("SE CONTRATO A UN PROVEEDOR DE MOTORES");
               this.logica.getpMotor()[i] = new Proveedores (this.logica.getSEMM(), this.logica.getSPM(), this.logica.getSCM(), this.logica.getAlamacenMotor(), 3, this.logica);
               this.logica.getpMotor()[i].start();
               aux = true;
               break;
            }
        }
        
    }//GEN-LAST:event_contratarMActionPerformed

    
    private void contratarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarPActionPerformed
        // TODO add your handling code here:
        
        boolean aux = false;
        if(this.logica.getProvInicialP()< this.logica.getMaxProvP()){
            this.logica.setProvInicialP(this.logica.getProvInicialP()+1);
            this.logica.getInterfaz().getProdPara().setText(Integer.toString(this.logica.getProvInicialP()));
        }
        
        for (int i = 0; i < this.logica.getProvInicialP(); i++) {
            if (this.logica.getpParabrisa()[i]== null && !aux) {
                System.out.println("SE CONTRATO A UN PROVEEDOR DE PARABRISAS");
               this.logica.getpParabrisa()[i] = new Proveedores (this.logica.getSEMP(), this.logica.getSPP(), this.logica.getSCP(), this.logica.getAlmacenParabrisa(), 2, this.logica);
               this.logica.getpParabrisa()[i].start();
               aux = true;
               break;
            }
        }
        
    }//GEN-LAST:event_contratarPActionPerformed

    private void cantEnsamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantEnsamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantEnsamActionPerformed

    private void prodParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodParaActionPerformed

    private void despedirRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirRActionPerformed
        // TODO add your handling code here:
        
          for (int i = 0; i < this.logica.getpRuedas().length; i++) {
            boolean despedir= false;
            //Si hay un proveedor
            if(this.logica.getpRuedas()[i]!= null && despedir == false){
                System.out.println("EL THREAD EN LA POSICION " + i + " SE ECUNETRA "+ this.logica.getpRuedas()[i].isActivo());
                System.out.println( "SE DESPIDIO A UN PROVEEDOR DE RUEDAS");
                this.logica.getpRuedas()[i].setActivo(false);
                System.out.println("EL THREAD EN LA POSICION " + i + " SE ECUNETRA "+ this.logica.getpRuedas()[i].isActivo());
                this.logica.getpRuedas()[i] = null;
                despedir= true;
                break;
            }
        }
        
        //Reflejamos los cambios en la vista
        if(this.logica.getProvInicialR()>0){
            this.logica.setProvInicialR(this.logica.getProvInicialR()-1);
            this.logica.getInterfaz().getProdRuedas().setText(Integer.toString(this.logica.getProvInicialR()));
        }
    
    }//GEN-LAST:event_despedirRActionPerformed

    private void contratarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarRActionPerformed
        // TODO add your handling code here:
        
       boolean aux = false;
        if(this.logica.getProvInicialR()< this.logica.getMaxProvR()){
            this.logica.setProvInicialR(this.logica.getProvInicialR()+1);
            this.logica.getInterfaz().getProdRuedas().setText(Integer.toString(this.logica.getProvInicialR()));
        }
        
        for (int i = 0; i < this.logica.getProvInicialR(); i++) {
            if (this.logica.getpRuedas()[i]== null && !aux) {
                System.out.println("SE CONTRATO A UN PROVEEDOR DE RUEDAS");
               this.logica.getpRuedas()[i] = new Proveedores (this.logica.getSEMR(), this.logica.getSPR(), this.logica.getSCR(), this.logica.getAlamacenRuedas(), 1, this.logica);
               this.logica.getpRuedas()[i].start();
               aux = true;
               break;
            }
        }
    }//GEN-LAST:event_contratarRActionPerformed

    private void despedirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirPActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < this.logica.getpParabrisa().length; i++) {
            boolean despedir= false;
            //Si hay un proveedor
            if(this.logica.getpParabrisa()[i]!= null && despedir == false){
                System.out.println( "SE DESPIDIO A UN PROVEEDOR DE PARABRISAS");
                this.logica.getpParabrisa()[i].setActivo(false);
                this.logica.getpParabrisa()[i] = null;
                despedir= true;
                break;
            }
        }
        
        //Reflejamos los cambios en la vista
        if(this.logica.getProvInicialP()>0){
            this.logica.setProvInicialP(this.logica.getProvInicialP()-1);
            this.logica.getInterfaz().getProdPara().setText(Integer.toString(this.logica.getProvInicialP()));
        }
    }//GEN-LAST:event_despedirPActionPerformed

    private void despedirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirMActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < this.logica.getpMotor().length; i++) {
            boolean despedir= false;
            //Si hay un proveedor
            if(this.logica.getpMotor()[i]!= null && despedir == false){
                System.out.println( "SE DESPIDIO A UN PROVEEDOR DE MOTORES");
                this.logica.getpMotor()[i].setActivo(false);
                this.logica.getpMotor()[i] = null;
                despedir= true;
                break;
            }
        }
        
        //Reflejamos los cambios en la vista
        if(this.logica.getProvInicialM()>0){
            this.logica.setProvInicialM(this.logica.getProvInicialM()-1);
            this.logica.getInterfaz().getProdMotor().setText(Integer.toString(this.logica.getProvInicialM()));
        }
    }//GEN-LAST:event_despedirMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < this.logica.getEnsamblador().length; i++) {
            boolean despedir= false;
            //Si hay un proveedor
            if(this.logica.getEnsamblador()[i]!= null && despedir == false){
                System.out.println("EL THREAD EN LA POSICION " + i + " SE ECUNETRA "+ this.logica.getEnsamblador()[i].isActivo());
                System.out.println( "SE DESPIDIO A UN ENSAMBLADOR");
                this.logica.getEnsamblador()[i].setActivo(false);
                System.out.println("EL THREAD EN LA POSICION " + i + " SE ECUNETRA "+ this.logica.getEnsamblador()[i].isActivo());
                this.logica.getEnsamblador()[i] = null;
                despedir= true;
                break;
            }
        }
        
        //Reflejamos los cambios en la vista
        if(this.logica.getEnsInicial()>0){
            this.logica.setEnsInicial(this.logica.getEnsInicial()-1);
            this.logica.getInterfaz().getCantEnsam().setText(Integer.toString(this.logica.getEnsInicial()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    //Getters y setters de la interfaz
    
    public JTextField getIntCantM() {
        return intCantM;
    }

    public void setIntCantM(JTextField intCantM) {
        this.intCantM = intCantM;
    }

    public JTextField getIntCantP() {
        return intCantP;
    }

    public void setIntCantP(JTextField intCantP) {
        this.intCantP = intCantP;
    }

    public JTextField getIntCantR() {
        return intCantR;
    }

    public void setIntCantR(JTextField intCantR) {
        this.intCantR = intCantR;
    }

    public JTextField getCarrosTerm() {
        return carrosTerm;
    }

    public void setCarrosTerm(JTextField carrosTerm) {
        this.carrosTerm = carrosTerm;
    }

    public JTextField getProdMotor() {
        return prodMotor;
    }

    public void setProdMotor(JTextField prodMotor) {
        this.prodMotor = prodMotor;
    }

    public JTextField getProdPara() {
        return prodPara;
    }

    public void setProdPara(JTextField prodPara) {
        this.prodPara = prodPara;
    }

    public JTextField getProdRuedas() {
        return prodRuedas;
    }

    public void setProdRuedas(JTextField prodRuedas) {
        this.prodRuedas = prodRuedas;
    }

    public JTextField getCantEnsam() {
        return cantEnsam;
    }

    public void setCantEnsam(JTextField cantEnsam) {
        this.cantEnsam = cantEnsam;
    }

    public JButton getContratarEnsambladores() {
        return contratarEnsambladores;
    }

    public void setContratarEnsambladores(JButton contratarEnsambladores) {
        this.contratarEnsambladores = contratarEnsambladores;
    }

    public JButton getContratarM() {
        return contratarM;
    }

    public void setContratarM(JButton contratarM) {
        this.contratarM = contratarM;
    }

    public JButton getContratarP() {
        return contratarP;
    }

    public void setContratarP(JButton contratarP) {
        this.contratarP = contratarP;
    }

    public JButton getContratarR() {
        return contratarR;
    }

    public void setContratarR(JButton contratarR) {
        this.contratarR = contratarR;
    }

    public JButton getDespedirM() {
        return despedirM;
    }

    public void setDespedirM(JButton despedirM) {
        this.despedirM = despedirM;
    }

    public JButton getDespedirP() {
        return despedirP;
    }

    public void setDespedirP(JButton despedirP) {
        this.despedirP = despedirP;
    }

    public JButton getDespedirR() {
        return despedirR;
    }

    public void setDespedirR(JButton despedirR) {
        this.despedirR = despedirR;
    }

    public JTextField getDiasDespacho() {
        return diasDespacho;
    }

    public void setDiasDespacho(JTextField diasDespacho) {
        this.diasDespacho = diasDespacho;
    }

    public JTextField getStatusGerente() {
        return statusGerente;
    }

    public void setStatusGerente(JTextField statusGerente) {
        this.statusGerente = statusGerente;
    }

    public JTextField getStatusJefe() {
        return statusJefe;
    }

    public void setStatusJefe(JTextField statusJefe) {
        this.statusJefe = statusJefe;
    }
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantEnsam;
    private javax.swing.JTextField carrosTerm;
    private javax.swing.JButton contratarEnsambladores;
    private javax.swing.JButton contratarM;
    private javax.swing.JButton contratarP;
    private javax.swing.JButton contratarR;
    private javax.swing.JButton despedirM;
    private javax.swing.JButton despedirP;
    private javax.swing.JButton despedirR;
    private javax.swing.JTextField diasDespacho;
    private javax.swing.JTextField intCantM;
    private javax.swing.JTextField intCantP;
    private javax.swing.JTextField intCantR;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField prodMotor;
    private javax.swing.JTextField prodPara;
    private javax.swing.JTextField prodRuedas;
    private javax.swing.JTextField statusGerente;
    private javax.swing.JTextField statusJefe;
    // End of variables declaration//GEN-END:variables
}
